# The Site Configuration

# 导入使用的主题 (你正在使用 Chirpy 主题)
theme: jekyll-theme-chirpy

# 网站的主要语言代码。如果和 `_data/locales` 中文件名匹配, 界面也会部分汉化。
# lang: en # 示例：英文
# lang: zh-CN # 示例：简体中文
lang: zh-CN

# 网站使用的时区。请根据你所在位置修改，例如 "Asia/Shanghai"。
timezone: Asia/Shanghai

# jekyll-seo-tag 插件的设置 (用于 SEO 优化) › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

# 网站标题 (显示在浏览器标签页、搜索结果等)
title: 天秋的博客

# 网站标语或副标题 (通常显示在标题下方)
tagline: 天(T)秋(Q)，来自辛弃疾的词“天凉好个秋”。abc，则是记录生活、分享思考的一点一滴。天秋有情，字母有声，TQabc.com，讲述博主点滴故事。

# 网站描述 (主要用于搜索引擎优化，告诉搜索引擎网站是关于什么的)
description: >- # 天秋的个人博客，主要记录日常生活中的点滴、心情随笔和一些思考感悟。分享真实的瞬间，感受生活的美好。

# 网站的完整 URL (协议 + 域名)。注意末尾不要加 '/'。
# 例如 'https://username.github.io' 或 'https://www.yourdomain.com'
url: "https://www.tqabc.com"

# GitHub 相关设置
github:
  # 你的 GitHub 用户名 (用于生成指向你 GitHub 主页的链接等)
  username: szwalu # change to your GitHub username

# Twitter 相关设置
twitter:
  # 你的 Twitter 用户名 (用于生成 Twitter Card 等)
  username: szwalu # change to your Twitter username

# 社交信息设置
social:
  # 你的全名。将作为文章的默认作者名和页脚的版权所有者显示。
  name: 天秋
  # 你的电子邮件地址 (可能会显示在联系方式等处)
  email: tq@woabc.com # change to your email address
  # 在页脚等处显示的社交链接列表。
  links:
    # 第一个链接通常用作版权所有者的链接。
    - https://twitter.com/username # 更改为你的 Twitter 主页
    - https://github.com/username # 更改为你的 GitHub 主页
    # 取消下面的注释 (#) 来添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 网站验证设置 (用于搜索引擎站长工具)
webmaster_verifications:
  google: # 填入 Google 验证码
  bing: # 填入 Bing 验证码
  alexa: # 填入 Alexa 验证码
  yandex: # 填入 Yandex 验证码
  baidu: # 填入 Baidu 验证码
  facebook: # 填入 Facebook 验证码

# ↑ --------------------------
# `jekyll-seo-tag` 设置结束

# 网站统计分析设置
analytics:
  google:
    # 填入你的 Google Analytics Measurement ID (G-XXXXXXXXXX)
    id:
  goatcounter:
    # 填入你的 GoatCounter ID
    id:
  umami:
    # 填入你的 Umami ID
    id:
    # 填入你的 Umami 域名
    domain:
  matomo:
    # 填入你的 Matomo ID
    id:
    # 填入你的 Matomo 域名
    domain:
  cloudflare:
    # 填入你的 Cloudflare Web Analytics token
    id:
  fathom:
    # 填入你的 Fathom Site ID
    id:

# 页面浏览量统计设置 (目前仅支持 GoatCounter)
pageviews:
  provider: # 可选值: 'goatcounter'

# 偏好的颜色主题设置。
# 留空则默认跟随系统设置，并在侧边栏左下角提供切换按钮。
# 可选值: 'light' (强制浅色), 'dark' (强制深色)。
theme_mode: # [light | dark]

# 媒体资源的 CDN 端点。(可选)
# 如果设置了，所有以 '/' 开头的媒体资源 (头像、文章图片、音视频) 路径前都会加上这个 CDN URL。
# 例如: 'https://cdn.com'
cdn:

# 侧边栏显示的头像图片。支持本地路径或 CORS 资源 URL。
avatar: /assets/img/my_avatar.png

# 网站范围的社交预览图片 URL (用于 SEO 的 `og:image` meta 标签)。
# 可以在文章的 Front Matter 中用 `page.image` 覆盖。
social_preview_image: # string, local or CORS resources

# 布尔值 (true/false)，文章中目录 (TOC) 功能的全局开关。
toc: true

# 评论系统设置
comments:
  # 评论系统的全局开关。留空表示禁用。可选值: 'disqus', 'utterances', 'giscus'
  provider: "giscus"
  # 各个评论系统的具体配置选项：
  # disqus:
    # 填入 Disqus 的 shortname (不是用户名)
    shortname:
  # utterances 设置 (基于 GitHub Issues)
  # utterances:
    # 你的 GitHub 仓库名 (<用户名>/<仓库名>)
    repo:
    # 文章与 Issue 的映射方式 (如 'pathname', 'url', 'title')
    issue_term:
  # Giscus 设置 (基于 GitHub Discussions)
  giscus:
    # 你的 GitHub 仓库名 (<用户名>/<仓库名>)
    repo: "szwalu/szwalu.github.io"
    # 你的仓库 ID (从 giscus.app 获取)
    repo_id: "R_kgDOOo721g"
    # Discussion 分类名称
    category: "博客评论"
    # Discussion 分类 ID (从 giscus.app 获取)
    category_id: "DIC_kwDOOo721s4CqH_o"
    # 文章与 Discussion 的映射方式 (可选, 默认 'pathname')
    mapping: "pathname"
    # 是否精确匹配 (可选, 默认 '0')
    strict: "0"
    # 评论框位置 (可选, 默认 'bottom')
    input_position: "bottom"
    # 评论框语言 (可选, 默认跟随 `site.lang`)
    lang: "zh-CN"
    # 是否启用 Reactions (点赞等) (可选, 默认 '1')
    reactions_enabled:

# (可选) 自托管静态资源 (如 CSS/JS) 设置 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    # 是否启用自托管 (true/false), 留空表示 false
    enabled:
    # 指定生效的 Jekyll 环境 (development 或 production), 留空表示两者都生效
    # 仅当 enabled 为 true 时有效
    env:

# PWA (Progressive Web App) 功能设置
pwa:
  # 是否启用 PWA 功能 (可安装到桌面) (true/false)
  enabled: true
  # PWA 离线缓存设置
  cache:
    # 是否启用 PWA 离线缓存 (true/false)
    enabled: true
    # 需要从 PWA 缓存中排除的路径列表 (例如其他共享同一域名的网站的 baseurl)
    deny_paths:
      # - "/example"

# 首页/列表页每页显示的文章数量
paginate: 10

# 网站的基础路径 (子目录)。如果网站部署在根目录, 则留空 ""。
# 注意: 这个设置通常建议放在 `url` 下方, 但这里放在了后面。
baseurl: ""

# ------------ 下面的选项通常不需要修改 ------------------

# Kramdown Markdown 渲染器设置
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;" # 注脚返回链接的符号
  syntax_highlighter: rouge          # 代码语法高亮器
  syntax_highlighter_opts:           # Rouge 高亮器选项
    css_class: highlight             # 代码块的 CSS 类名
    # default_lang: console
    span:
      line_numbers: false            # 行内代码块不显示行号
    block:
      line_numbers: true             # 代码块显示行号
      start_line: 1                  # 行号从 1 开始

# Jekyll Collections 设置 (用于处理 _tabs 文件夹等)
collections:
  tabs:
    output: true                     # 输出 _tabs 目录下的文件为页面
    sort_by: order                   # 按 Front Matter 中的 'order' 字段排序

# 默认 Front Matter 设置
defaults:
  - scope:
      path: ""                       # 应用于所有文件
      type: posts                  # 限定为 posts 类型
    values:
      layout: post                 # 默认使用 post 布局
      comments: true               # 默认启用评论
      toc: true                    # 默认启用目录
      # 不要修改下面的 permalink, 除非你清楚其影响并能更新所有相关链接
      permalink: /posts/:title/    # 文章的永久链接格式
  - scope:
      path: _drafts                # 应用于草稿
    values:
      comments: false              # 草稿默认禁用评论
  - scope:
      path: ""
      type: tabs                   # 应用于 tabs 类型 (即 _tabs 文件夹下的文件)
    values:
      layout: page                 # 默认使用 page 布局
      permalink: /:title/          # tabs 页面的永久链接格式

# Sass/SCSS 编译设置
sass:
  style: compressed                # 输出压缩后的 CSS

# HTML 压缩设置
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# 构建网站时要排除的文件/文件夹列表
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

# jekyll-archives 插件设置 (用于自动生成分类和标签页面)
jekyll-archives:
  enabled: [categories, tags]      # 启用分类和标签归档页
  layouts:
    category: category             # 分类页使用的布局 (来自 _layouts/category.html)
    tag: tag                       # 标签页使用的布局 (来自 _layouts/tag.html)
  permalinks:
    tag: /tags/:name/              # 标签页的 URL 格式
    category: /categories/:name/   # 分类页的 URL 格式
